### ISSUE TITLE
Why not release in binaries

### ISSUE THREAD

**Issue by t829702** [albertodonato/h2static#11]
one of the Go language benefit is to cross build binaries to many different architecture / platform (s), as many other Go projects do, they release pre-built binaries for some major platforms (Linux, Mac, Windows ...  x  amd64 arm64 ...)

I was looking for such a simple tool to serve some files over the Internet temporarily for demo purpose, so the https and a simple user:pass authentication is good enough, just as this h2static provides, it could be good for this task, but did not figure out where are the binaries, spent 5 minutes and gave up

https://github.com/m3ng9i/ran/releases  then I found this and use instead...

**Comment by albertodonato** [comment]
I might look into using Github actions to build go binaries.

Currently, you can either build it as described in the readme, or use the snap, which is available for multiple platforms.

**Comment by t829702** [comment]
I spent 5 minutes on how to download a snap binary, and how to extract the binary from a snap package, without trust to what `snap` does, but did not figure it out in 5 minutes and have gave up

**Comment by albertodonato** [comment]
I'm not sure I understand. As described in https://github.com/albertodonato/h2static#install-from-snap, you can install the snap with one command (assuming you're on a supported arch/distro).

**Comment by albertodonato** [comment]
Binary packages are now released.
